//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCaptiva_Service.Tests.InCaptivaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/inCaptiva_Service")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompletedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> TimeUsedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompletedTime {
            get {
                return this.CompletedTimeField;
            }
            set {
                if ((this.CompletedTimeField.Equals(value) != true)) {
                    this.CompletedTimeField = value;
                    this.RaisePropertyChanged("CompletedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> TimeUsed {
            get {
                return this.TimeUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeUsedField, value) != true)) {
                    this.TimeUsedField = value;
                    this.RaisePropertyChanged("TimeUsed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://schemas.datacontract.org/2004/07/inCaptiva_Service")]
    [System.SerializableAttribute()]
    public partial class Worker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/inCaptiva_Service")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompletedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> TimeUsedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompletedTime {
            get {
                return this.CompletedTimeField;
            }
            set {
                if ((this.CompletedTimeField.Equals(value) != true)) {
                    this.CompletedTimeField = value;
                    this.RaisePropertyChanged("CompletedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> TimeUsed {
            get {
                return this.TimeUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeUsedField, value) != true)) {
                    this.TimeUsedField = value;
                    this.RaisePropertyChanged("TimeUsed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkEntry", Namespace="http://schemas.datacontract.org/2004/07/inCaptiva_Service")]
    [System.SerializableAttribute()]
    public partial class WorkEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompletedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> TimeUsedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CompletedTime {
            get {
                return this.CompletedTimeField;
            }
            set {
                if ((this.CompletedTimeField.Equals(value) != true)) {
                    this.CompletedTimeField = value;
                    this.RaisePropertyChanged("CompletedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> TimeUsed {
            get {
                return this.TimeUsedField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeUsedField, value) != true)) {
                    this.TimeUsedField = value;
                    this.RaisePropertyChanged("TimeUsed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerID {
            get {
                return this.WorkerIDField;
            }
            set {
                if ((this.WorkerIDField.Equals(value) != true)) {
                    this.WorkerIDField = value;
                    this.RaisePropertyChanged("WorkerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InCaptivaService.IInCaptivaService")]
    public interface IInCaptivaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetData", ReplyAction="http://tempuri.org/IInCaptivaService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetData", ReplyAction="http://tempuri.org/IInCaptivaService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetTasks", ReplyAction="http://tempuri.org/IInCaptivaService/GetTasksResponse")]
        System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Task> GetTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetTasks", ReplyAction="http://tempuri.org/IInCaptivaService/GetTasksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Task>> GetTasksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetWorkers", ReplyAction="http://tempuri.org/IInCaptivaService/GetWorkersResponse")]
        System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Worker> GetWorkers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetWorkers", ReplyAction="http://tempuri.org/IInCaptivaService/GetWorkersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Worker>> GetWorkersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetProjects", ReplyAction="http://tempuri.org/IInCaptivaService/GetProjectsResponse")]
        System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Project> GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetProjects", ReplyAction="http://tempuri.org/IInCaptivaService/GetProjectsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Project>> GetProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetWorkEntries", ReplyAction="http://tempuri.org/IInCaptivaService/GetWorkEntriesResponse")]
        System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.WorkEntry> GetWorkEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/GetWorkEntries", ReplyAction="http://tempuri.org/IInCaptivaService/GetWorkEntriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.WorkEntry>> GetWorkEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewWorker", ReplyAction="http://tempuri.org/IInCaptivaService/NewWorkerResponse")]
        void NewWorker(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewWorker", ReplyAction="http://tempuri.org/IInCaptivaService/NewWorkerResponse")]
        System.Threading.Tasks.Task NewWorkerAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewProject", ReplyAction="http://tempuri.org/IInCaptivaService/NewProjectResponse")]
        void NewProject(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewProject", ReplyAction="http://tempuri.org/IInCaptivaService/NewProjectResponse")]
        System.Threading.Tasks.Task NewProjectAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewTask", ReplyAction="http://tempuri.org/IInCaptivaService/NewTaskResponse")]
        void NewTask(int projectID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewTask", ReplyAction="http://tempuri.org/IInCaptivaService/NewTaskResponse")]
        System.Threading.Tasks.Task NewTaskAsync(int projectID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewWorkEntry", ReplyAction="http://tempuri.org/IInCaptivaService/NewWorkEntryResponse")]
        void NewWorkEntry(int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/NewWorkEntry", ReplyAction="http://tempuri.org/IInCaptivaService/NewWorkEntryResponse")]
        System.Threading.Tasks.Task NewWorkEntryAsync(int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/StartBreak", ReplyAction="http://tempuri.org/IInCaptivaService/StartBreakResponse")]
        void StartBreak(int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/StartBreak", ReplyAction="http://tempuri.org/IInCaptivaService/StartBreakResponse")]
        System.Threading.Tasks.Task StartBreakAsync(int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EndBreak", ReplyAction="http://tempuri.org/IInCaptivaService/EndBreakResponse")]
        void EndBreak(int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EndBreak", ReplyAction="http://tempuri.org/IInCaptivaService/EndBreakResponse")]
        System.Threading.Tasks.Task EndBreakAsync(int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditWorker", ReplyAction="http://tempuri.org/IInCaptivaService/EditWorkerResponse")]
        void EditWorker(int workerID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditWorker", ReplyAction="http://tempuri.org/IInCaptivaService/EditWorkerResponse")]
        System.Threading.Tasks.Task EditWorkerAsync(int workerID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditWorkEntry", ReplyAction="http://tempuri.org/IInCaptivaService/EditWorkEntryResponse")]
        void EditWorkEntry(int entryID, System.Nullable<System.DateTime> start, int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditWorkEntry", ReplyAction="http://tempuri.org/IInCaptivaService/EditWorkEntryResponse")]
        System.Threading.Tasks.Task EditWorkEntryAsync(int entryID, System.Nullable<System.DateTime> start, int workerID, int taskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditTask", ReplyAction="http://tempuri.org/IInCaptivaService/EditTaskResponse")]
        void EditTask(int taskID, string description, System.Nullable<System.DateTime> start, int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditTask", ReplyAction="http://tempuri.org/IInCaptivaService/EditTaskResponse")]
        System.Threading.Tasks.Task EditTaskAsync(int taskID, string description, System.Nullable<System.DateTime> start, int projectID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditProject", ReplyAction="http://tempuri.org/IInCaptivaService/EditProjectResponse")]
        void EditProject(int projectID, string name, System.Nullable<System.DateTime> start);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/EditProject", ReplyAction="http://tempuri.org/IInCaptivaService/EditProjectResponse")]
        System.Threading.Tasks.Task EditProjectAsync(int projectID, string name, System.Nullable<System.DateTime> start);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteWorker", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteWorkerResponse")]
        string DeleteWorker(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteWorker", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteWorkerResponse")]
        System.Threading.Tasks.Task<string> DeleteWorkerAsync(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteWorkEntry", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteWorkEntryResponse")]
        string DeleteWorkEntry(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteWorkEntry", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteWorkEntryResponse")]
        System.Threading.Tasks.Task<string> DeleteWorkEntryAsync(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteTask", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteTaskResponse")]
        string DeleteTask(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteTask", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteTaskResponse")]
        System.Threading.Tasks.Task<string> DeleteTaskAsync(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteProject", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteProjectResponse")]
        string DeleteProject(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/DeleteProject", ReplyAction="http://tempuri.org/IInCaptivaService/DeleteProjectResponse")]
        System.Threading.Tasks.Task<string> DeleteProjectAsync(int workerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/ResetService", ReplyAction="http://tempuri.org/IInCaptivaService/ResetServiceResponse")]
        void ResetService(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInCaptivaService/ResetService", ReplyAction="http://tempuri.org/IInCaptivaService/ResetServiceResponse")]
        System.Threading.Tasks.Task ResetServiceAsync(string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInCaptivaServiceChannel : InCaptiva_Service.Tests.InCaptivaService.IInCaptivaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InCaptivaServiceClient : System.ServiceModel.ClientBase<InCaptiva_Service.Tests.InCaptivaService.IInCaptivaService>, InCaptiva_Service.Tests.InCaptivaService.IInCaptivaService {
        
        public InCaptivaServiceClient() {
        }
        
        public InCaptivaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InCaptivaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InCaptivaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InCaptivaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Task> GetTasks() {
            return base.Channel.GetTasks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Task>> GetTasksAsync() {
            return base.Channel.GetTasksAsync();
        }
        
        public System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Worker> GetWorkers() {
            return base.Channel.GetWorkers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Worker>> GetWorkersAsync() {
            return base.Channel.GetWorkersAsync();
        }
        
        public System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Project> GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.Project>> GetProjectsAsync() {
            return base.Channel.GetProjectsAsync();
        }
        
        public System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.WorkEntry> GetWorkEntries() {
            return base.Channel.GetWorkEntries();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InCaptiva_Service.Tests.InCaptivaService.WorkEntry>> GetWorkEntriesAsync() {
            return base.Channel.GetWorkEntriesAsync();
        }
        
        public void NewWorker(string name) {
            base.Channel.NewWorker(name);
        }
        
        public System.Threading.Tasks.Task NewWorkerAsync(string name) {
            return base.Channel.NewWorkerAsync(name);
        }
        
        public void NewProject(string name) {
            base.Channel.NewProject(name);
        }
        
        public System.Threading.Tasks.Task NewProjectAsync(string name) {
            return base.Channel.NewProjectAsync(name);
        }
        
        public void NewTask(int projectID, string description) {
            base.Channel.NewTask(projectID, description);
        }
        
        public System.Threading.Tasks.Task NewTaskAsync(int projectID, string description) {
            return base.Channel.NewTaskAsync(projectID, description);
        }
        
        public void NewWorkEntry(int workerID, int taskID) {
            base.Channel.NewWorkEntry(workerID, taskID);
        }
        
        public System.Threading.Tasks.Task NewWorkEntryAsync(int workerID, int taskID) {
            return base.Channel.NewWorkEntryAsync(workerID, taskID);
        }
        
        public void StartBreak(int workerID, int taskID) {
            base.Channel.StartBreak(workerID, taskID);
        }
        
        public System.Threading.Tasks.Task StartBreakAsync(int workerID, int taskID) {
            return base.Channel.StartBreakAsync(workerID, taskID);
        }
        
        public void EndBreak(int workerID, int taskID) {
            base.Channel.EndBreak(workerID, taskID);
        }
        
        public System.Threading.Tasks.Task EndBreakAsync(int workerID, int taskID) {
            return base.Channel.EndBreakAsync(workerID, taskID);
        }
        
        public void EditWorker(int workerID, string name) {
            base.Channel.EditWorker(workerID, name);
        }
        
        public System.Threading.Tasks.Task EditWorkerAsync(int workerID, string name) {
            return base.Channel.EditWorkerAsync(workerID, name);
        }
        
        public void EditWorkEntry(int entryID, System.Nullable<System.DateTime> start, int workerID, int taskID) {
            base.Channel.EditWorkEntry(entryID, start, workerID, taskID);
        }
        
        public System.Threading.Tasks.Task EditWorkEntryAsync(int entryID, System.Nullable<System.DateTime> start, int workerID, int taskID) {
            return base.Channel.EditWorkEntryAsync(entryID, start, workerID, taskID);
        }
        
        public void EditTask(int taskID, string description, System.Nullable<System.DateTime> start, int projectID) {
            base.Channel.EditTask(taskID, description, start, projectID);
        }
        
        public System.Threading.Tasks.Task EditTaskAsync(int taskID, string description, System.Nullable<System.DateTime> start, int projectID) {
            return base.Channel.EditTaskAsync(taskID, description, start, projectID);
        }
        
        public void EditProject(int projectID, string name, System.Nullable<System.DateTime> start) {
            base.Channel.EditProject(projectID, name, start);
        }
        
        public System.Threading.Tasks.Task EditProjectAsync(int projectID, string name, System.Nullable<System.DateTime> start) {
            return base.Channel.EditProjectAsync(projectID, name, start);
        }
        
        public string DeleteWorker(int workerID) {
            return base.Channel.DeleteWorker(workerID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteWorkerAsync(int workerID) {
            return base.Channel.DeleteWorkerAsync(workerID);
        }
        
        public string DeleteWorkEntry(int workerID) {
            return base.Channel.DeleteWorkEntry(workerID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteWorkEntryAsync(int workerID) {
            return base.Channel.DeleteWorkEntryAsync(workerID);
        }
        
        public string DeleteTask(int workerID) {
            return base.Channel.DeleteTask(workerID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteTaskAsync(int workerID) {
            return base.Channel.DeleteTaskAsync(workerID);
        }
        
        public string DeleteProject(int workerID) {
            return base.Channel.DeleteProject(workerID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteProjectAsync(int workerID) {
            return base.Channel.DeleteProjectAsync(workerID);
        }
        
        public void ResetService(string password) {
            base.Channel.ResetService(password);
        }
        
        public System.Threading.Tasks.Task ResetServiceAsync(string password) {
            return base.Channel.ResetServiceAsync(password);
        }
    }
}
